# Generated by Django 2.2 on 2021-01-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_room_square'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_square',
        ),
    ]
