# Generated by Django 2.2 on 2021-01-27 08:40
import random

from django.db import migrations, models


def random_room_square(apps, schema_editor):
    Room = apps.get_model('main', 'Room')
    for room in Room.objects.all():
        room.room_square = float(random.randint(1, 100))
        room.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_remove_room_room_square'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_square',
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.RunPython(random_room_square),
    ]
