# Generated by Django 3.1.6 on 2021-02-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_hotel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
