# Generated by Django 3.1.6 on 2021-02-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_hotel_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='features',
            field=models.ManyToManyField(blank=True, to='main.HotelFeature'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
