# Generated by Django 3.1.6 on 2021-02-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210219_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['-created_at']},
        ),
    ]
