# Generated by Django 3.1.7 on 2021-03-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_hotel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=150)),
                ('city_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'hotelcountry',
                'managed': False,
            },
        ),
    ]
