# Generated by Django 2.2 on 2021-02-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20210201_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
