# Generated by Django 3.1.4 on 2021-02-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20210204_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
