# Generated by Django 3.1.4 on 2021-02-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='N', max_length=1),
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
