# Generated by Django 3.1.4 on 2021-02-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210201_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('U', 'User'), ('O', 'Owner')], default='U', max_length=1),
        ),
    ]
